let
    Source = Csv.Document(File.Contents("C:\Users\user\OneDrive\Documents\ERNEST PROJECTS\CAR PRICES (PBI)\car_prices.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"year", Int64.Type}, {"make", type text}, {"model", type text}, {"trim", type text}, {"body", type text}, {"transmission", type text}, {"vin", type text}, {"state", type text}, {"condition", Int64.Type}, {"odometer", Int64.Type}, {"color", type text}, {"interior", type text}, {"seller", type text}, {"mmr", Int64.Type}, {"sellingprice", Int64.Type}, {"saledate", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"model", "trim", "body", "condition", "odometer", "interior"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"vin"}),
    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Filtered Rows" = Table.SelectRows(#"Removed Blank Rows", each [make] <> null and [make] <> ""),
    #"Removed Blank Rows1" = Table.SelectRows(#"Filtered Rows", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Blank Rows1",{{"make", Text.Proper, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","Vw","Volkswagen",Replacer.ReplaceText,{"make"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Bmw","BMW",Replacer.ReplaceText,{"make"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Landrover","Land Rover",Replacer.ReplaceText,{"make"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Mercedes-Benz","Mercedes",Replacer.ReplaceText,{"make"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Mercedes-B","Mercedes",Replacer.ReplaceText,{"make"}),
    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value4", each [transmission] <> null and [transmission] <> ""),
    #"Removed Blank Rows2" = Table.SelectRows(#"Filtered Rows1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Capitalized Each Word1" = Table.TransformColumns(#"Removed Blank Rows2",{{"transmission", Text.Proper, type text}}),
    #"Sorted Rows" = Table.Sort(#"Capitalized Each Word1",{{"state", Order.Ascending}}),
    #"Removed Top Rows" = Table.Skip(#"Sorted Rows",2),
    #"Capitalized Each Word2" = Table.TransformColumns(#"Removed Top Rows",{{"color", Text.Proper, type text}, {"seller", Text.Proper, type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Capitalized Each Word2", each true),
    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows2", each [color] <> null and [color] <> ""),
    #"Extracted First Characters" = Table.TransformColumns(#"Filtered Rows3", {{"saledate", each Text.Start(_, 15), type text}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Extracted First Characters",{{"saledate", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"year", "Year of manufacture"}, {"make", "Brand"}, {"transmission", "Transmission"}, {"vin", "VIN"}, {"state", "State"}, {"color", "Colour"}, {"seller", "Seller"}, {"mmr", "MMR"}, {"sellingprice", "Sales"}, {"saledate", "Date Sold"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"MMR"}),
    #"Filtered Rows4" = Table.SelectRows(#"Removed Columns1", each [Date Sold] <> null and [Date Sold] <> ""),
    #"Removed Blank Rows3" = Table.SelectRows(#"Filtered Rows4", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Filtered Rows5" = Table.SelectRows(#"Removed Blank Rows3", each [Sales] <> null and [Sales] <> ""),
    #"Removed Blank Rows4" = Table.SelectRows(#"Filtered Rows5", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Replaced Value5" = Table.ReplaceValue(#"Removed Blank Rows4","--","Gold",Replacer.ReplaceText,{"Colour"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","—","Gold",Replacer.ReplaceText,{"Colour"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","pr","pa",Replacer.ReplaceText,{"State"}),
    #"Split Column by Position" = Table.SplitColumn(Table.TransformColumnTypes(#"Replaced Value7", {{"Date Sold", type text}}, "en-GB"), "Date Sold", Splitter.SplitTextByRepeatedLengths(6), {"Date Sold.1", "Date Sold.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Position",{{"Date Sold.1", type text}, {"Date Sold.2", Int64.Type}}),
    #"Replaced Value8" = Table.ReplaceValue(#"Changed Type2",2015,2023,Replacer.ReplaceValue,{"Date Sold.2"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8",2014,2022,Replacer.ReplaceValue,{"Date Sold.2"}),
    #"Inserted Merged Column" = Table.AddColumn(#"Replaced Value9", "Date Sold", each Text.Combine({[Date Sold.1], Text.From([Date Sold.2], "en-GB")}, ""), type text),
    #"Removed Columns2" = Table.RemoveColumns(#"Inserted Merged Column",{"Date Sold.1", "Date Sold.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Columns2",{{"Date Sold", type date}}),
    #"Appended Query" = Table.Combine({#"Changed Type3", car_prices_2}),
    #"Replaced Value10" = Table.ReplaceValue(#"Appended Query","-"," ",Replacer.ReplaceText,{"Seller"}),
    #"Removed Blank Rows5" = Table.SelectRows(#"Replaced Value10", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Filtered Rows6" = Table.SelectRows(#"Removed Blank Rows5", each [Date Sold] <> null and [Date Sold] <> ""),
    #"Filtered Rows7" = Table.SelectRows(#"Filtered Rows6", each [Date Sold] <> null and [Date Sold] <> ""),
    #"Removed Blank Rows6" = Table.SelectRows(#"Filtered Rows7", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
in
    #"Removed Blank Rows6"